### ISSUE TITLE
Reading the APSIM file through R

### ISSUE THREAD

**Issue by harsh-pathak-purdue** [femiguez/apsimx#107]
Greetings all,

Does this following capture your interest:

Please note that I am trying to read the APSIM file (not the example), through R using the following script 
`
sim <- read_apsimx("v1", src.dir = file_path, value = "report", simplify = TRUE)
`
But getting the following error: No report tables found.
Although the report table is already there in APSIM user-interface.

Appreciate your time, help, and suggestions

**Comment by harsh-pathak-purdue** [comment]
Thanks for your quick reply!

I used APSIM next generation (2022.6.7044.0) and simulated the tillage experiment using 'Operations' class and was further trying to use R to read reports and data coming through APSIM. Weather and soil data was downloaded using the APSIM interface only. 

Here is the screenshot of the attached class file.
![image](https://user-images.githubusercontent.com/89477883/209719303-b96725db-3ba7-4857-a214-c1a388bd6a21.png)

**Comment by femiguez** [comment]
You have provided some detail, but not a reproducible example. If your '.apsimx' file is called 'Tillage_example.apsimx' you can try to run it from R using

```
sim <- apsimx("Tillage_example.apsimx", src.dir = file_path)
```
Given that the results are stored in "Report", you do not need to set 'value'. If you already ran the simulations using the GUI, you can read in the results into R using

```
sim <- read_apsimx("Tillage_example.db", src.dir = file_path)
```
Rather than looking in the APSIM GUI, you need to look in the directories. You can do this using function 'dir' in R for example

**Comment by harsh-pathak-purdue** [comment]
Thanks much for helping me out!

**Comment by femiguez** [comment]
I consider this closed
