### ISSUE TITLE
Error:   An assembly specified in the application dependencies manifest (Models.deps.json) was not found

### ISSUE THREAD

**Issue by zkwabm** [femiguez/apsimx#114]
Hi,

I installed the latest version of  APSIMX (2023.2.7147.0) and apsim

When I try:
`sim <- apsimx("Sugarcane.apsimx")`

I get the error:

```
Error:
  An assembly specified in the application dependencies manifest (Models.deps.json) was not found:
    package: 'Microsoft.Win32.Registry', version: '5.0.0'
    path: 'runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll'
Warning message:
In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :
  running command 'C:\Windows\system32\cmd.exe /c C:\PROGRA~1\APSIM2023.2.7147.0\bin\Models.exe .\baseM_sugarcane.apsimx' had status 32908
```
And tried several versions of apsimx, such as 7131, 7136, etc. And still got the same error.

I have already installed the .net framework 5.0. 

When I try:

`sim <- apsim("Sugar.apsim")`

It runs successfully.

Any idea how to resolve this error? Thank you!

**Comment by femiguez** [comment]
@zkwabm This might be a problem with APSIM and not with the 'apsimx' package. Notice that you are attempting two different things. One is to run APSIM Next Gen (.apsimx file) and the other running APSIM Classic (.apsim) from R. For Next Gen, I suggest installing a version from last year (2022), since there are some issues with newer versions.

**Comment by zkwabm** [comment]
@femiguez Yes, you are right!

I just didn't find the right version of APSIM NG, the 7130 version (the last version of 2022) does work.

Thank you!

**Comment by femiguez** [comment]
I will close this unless you have other questions
