### ISSUE TITLE
Simulation Error in after Modifying Rotation Files

### ISSUE THREAD

**Issue by smkuhlani** [femiguez/apsimx#131]
Hi Femi,

I am creating a Maize-Peanut rotation simulation. I am creating this by editing the default Maize-Wheat rotation. The simulation is however throwing an error: 'Test condition '[WheatManager].Script.CanSow' returned nothing', yet i have replaced all the Wheat components. I have attached the error screenshot and the simulation file.

Cheers
[MaizePeanutRotation.zip](https://github.com/femiguez/apsimx/files/12498012/MaizePeanutRotation.zip)

![image](https://github.com/femiguez/apsimx/assets/34687653/3a88e5f8-1e5f-4bb1-8f37-ec0f57ab6cb5)

**Comment by femiguez** [comment]
@smkuhlani I looked at this file and it is a factorial generated using APSIM. The question is not related to the 'apsimx' R package I support here AFAIK. If you have an issue or question related to the package I would be happy to tackle that. Otherwise, I'll be closing this as out of scope.
I can offer a suggestion of using the package to create simulations instead of the 'Factors' feature in APSIM, but either way is suitable
