### ISSUE TITLE
Error when run apsimx function 

### ISSUE THREAD

**Issue by Chloe0317** [femiguez/apsimx#28]
Hey Fernando,

I'm having some trouble running apsimx files using the ```apsimx``` function, e.g. when using ```out <- apsimx('mysims.apsimx', value = 'none')```, it prompted the windows to open mysims.apsimx in the APSIM Next Gen GUI. Then the R just showed busy and I have to manually terminate the process. Does that suppose to happen please? If it doesn't, what might be the reason for this please?

Also, I think in the ```auto_detect_apsimx()``` function, on line 175, instead of apsim.options, shouldn't it be apsimx.options?

https://github.com/femiguez/apsimx/blob/6c3b1b2e27fa7d9a0f7b9071cb3778dac2b26a4f/R/apsimx.R#L175

I set my apsimx path using ```apsimx_options```, and it returned 
```
Error in auto_detect_apsimx() : 
  Could not find APSIM-X in the Windows Registry
```
so I set the apsim.options$exe.path to my NG.exe too but I ran into the freeze and not proceed problem described earlier. 

Thank you!

**Comment by Chloe0317** [comment]
Also, I'm running a self-compiled custom build version of APSIMX please. Thanks!

**Comment by femiguez** [comment]
Hey Chloe,

Can you let me know what does your path look like? I suspect that when you set the path in apsimx_options it should be 

"C:/.../APSIM2021.XX.XX.XXXX/Bin/Models.exe" instead of something which ends in "NG.exe".

That might fix your problem.

Also, let me know what do you get when you run

`apsimx:::auto_detect_apsimx()`

At the R command line.

However, you did find a bug, I think.

**Comment by Chloe0317** [comment]
Hi Fernando,
When I run ```apsimx:::auto_detect_apsimx()```, I get the following error

apsimx:::auto_detect_apsimx()
Error in apsimx:::auto_detect_apsimx() : 
  Could not find APSIM-X in the Windows Registry
In addition: Warning message:
In apsimx:::auto_detect_apsimx() :
  Searching the Windows registry for APSIM-X


Also, may I suggest that for the read_apsimx function (or just the apsimx function), allow the ```value``` term to be user-defined please? Maybe value default to report but if user has defined value then the user-defined value is used. 

For example, if I have several different reports named differently, i.e. my report df is not named report per se, the current code returns ```Error: no such table: Report```, even when ```value = "all"```, since tbl0 cannot be read. 

Thank you very much!

**Comment by femiguez** [comment]
It is a good suggestion to change the way I handle the value argument in 'read_apsimx'. I guess all the examples I worked with used 'Report' that's why I have not had the need to change it. Could you send me an example of the db created by the Apsim run so that I can test it? If you prefer not to post it here you can send it to my email. Either femiguez (at) iastate.edu or fer.eze.miguez (at) gmail.com.

The other bug related to the auto_detect_apsimx is fixed on github. If you install using

`remotes::install_github("femiguez/apsimx")`

It should be fixed, but you might want to wait until I address the issue with 'read_apsimx'

**Comment by femiguez** [comment]
Thanks for the suggestion. I will probably address it in a different way, so that it does not break other code.

**Comment by Chloe0317** [comment]
Hi Fernando,
 
Of course. Thank you very much!
I just saw this but if you try it using the Single Tree Example.apsimx under the Examples/Agroforestry/ folder, it reported both Report and a DailyReport, the current method will not return the DailyReport. I've also attached a copy of my simulations too. 
Thanks in advance.
[DalyupSimple.zip](https://github.com/femiguez/apsimx/files/6032528/DalyupSimple.zip)

**Comment by femiguez** [comment]
Thanks for the feedback Chloe. I greatly appreciate it. I just pushed an update that will return the report if there is one available (regardless of what it is called). If you want a specific report you should be able to specify it by doing 'value = ReportName'. If you can test it that would be great!

**Comment by femiguez** [comment]
Sorry! I left a dumb bug still in the code. Now it is fixed. It seems to be working fine now. It's possible I did not catch all the possible scenarios still, so will need to test more.

**Comment by Chloe0317** [comment]
Hi Fernando,

Thank you for fixing the code! Much appreciated!

**Comment by femiguez** [comment]
Thank you for pointing this out! This paves the way for doing multi-simulation optimization in NextGen. I have implemented this in Classic, but it would need a few tweaks to get it to work in NextGen.

**Comment by femiguez** [comment]
This seems to be resolved. I'll close it for now.
