### ISSUE TITLE
No Report Tables Found Error: On Trying to Simulate After Replacing a Soil File

### ISSUE THREAD

**Issue by tuliscot** [femiguez/apsimx#58]
Hallo APSIMers,
I am having a feel of the package using the examples on the package.
I have extracted a new soil profile from the 'get_isric_soil_profile' function . I  have replaced the existing file using the function 'edit_apsimx_replace_soil_profile'. On running the simulation i get an error: 
-----------------------------------------------------------
Error in read_apsimx(file = sub("apsimx", "db", file), src.dir = src.dir,  : 
  No report tables found
In addition: Warning message:
In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :
  running command 'C:\WINDOWS\system32\cmd.exe /c C:\PROGRA~1\APSIM2021.05.21.5444\Bin\Models.exe C:\Users\xxxxx
[LinkedSoil_notSimulating.txt](https://github.com/femiguez/apsimx/files/7180570/LinkedSoil_notSimulating.txt)
\OneDrive\Documents\R\win-library\4.0\apsimx\extdata\Maize-edited.apsimx' had status 1
----------------------------------------------------------

I have attached the script giving me the error.

Cheers

**Comment by femiguez** [comment]
Soils returned from ISRIC need to be examined carefully before they can be used in APSIM. Before running this code make sure you choose a directory in R for which you have read/write permissions. The error was caused by some soil property combinations which are thought to be incompatible by APSIM. In the code below I modify them.

```
library(apsimx)
apsimx_options(warn.versions = FALSE)

ex.dir <- auto_detect_apsimx_examples()

file.copy(file.path(ex.dir, "Maize.apsimx"), ".")

soil.isric <- get_isric_soil_profile(lonlat = c(-93, 42))

soil.isric$soil$BD <- soil.isric$soil$BD * 0.86
soil.isric$soil$crop.LL <- soil.isric$soil$LL15 + 0.01

plot(soil.isric)
plot(soil.isric, property = "water")

edit_apsimx_replace_soil_profile("Maize.apsimx", soil.profile = soil.isric)

sim <- apsimx("Maize-edited.apsimx")
```

**Comment by tuliscot** [comment]
Works well. Thank you!

**Comment by femiguez** [comment]
Great! Feel free to open a new issue if you have any other questions.

**Comment by LenLon** [comment]
Interesting! Mind elaborating a bit on why you modify the ISRIC soils? This line reminds me of the "LL15 below AirDry" problem:

`soil.isric$soil$crop.LL <- soil.isric$soil$LL15 + 0.01`

But I can't follow the factor for bulk density. We also fix up the crop water extraction parameters according to the ApSoil protocol (either Dalgliesh or Cichota et al, can't remember). Couldn't that be implemented in the get_isric_soil_profile function?

**Comment by femiguez** [comment]
@LenLon This was an old issue. Since then I created the internal function that tries to 'fix' a soil profile. Catching issues before they are a problem when you run APSIM. Are you having problems with 'get_isric_soil_profile'? If you report those specifically, I can try to implement more general solutions. Recently, we found problems when creating synthetic soil profiles that 'slip through the crack' and end up causing errors in APSIM. You can also generate soil profiles using 'get_worldmodeler_soil_profile'.
